"use client";

import { forwardRef, useEffect, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode } from "react";
import { AnimatePresence, motion } from "framer-motion";

type ButtonVariant = "primary" | "secondary" | "ghost" | "danger" | "gold";
type ButtonSize = "sm" | "md" | "lg";
interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> { variant?: ButtonVariant; size?: ButtonSize; loading?: boolean; }
const variantClass: Record<ButtonVariant,string> = {
  primary:"bg-[#641F2B] text-[#F7F5F0] hover:bg-[#762735] border border-[#7b303e] shadow-[0_12px_30px_rgba(100,31,43,.28)]",
  secondary:"bg-[#18263A] text-[#F7F5F0] border border-[#32445d] hover:border-[#B99A62] hover:bg-[#203149] shadow-[0_8px_22px_rgba(0,0,0,.16)]",
  ghost:"bg-transparent text-[#D7D2C9] hover:bg-white/5 border border-transparent",
  danger:"bg-[#7d2929] text-white hover:bg-[#963434] border border-transparent shadow-[0_10px_24px_rgba(125,41,41,.22)]",
  gold:"bg-[#8A6A3A] text-[#F7F5F0] hover:bg-[#A07C45] border border-[#B99A62] shadow-[0_12px_30px_rgba(138,106,58,.25)]",
};
const sizeClass: Record<ButtonSize,string> = { sm:"h-9 px-4 text-xs rounded-lg", md:"h-11 px-5 text-sm rounded-lg", lg:"h-13 px-7 text-base rounded-xl" };
export const Button = forwardRef<HTMLButtonElement,ButtonProps>(function Button({variant="primary",size="md",loading,className="",disabled,children,...rest},ref){return <button ref={ref} className={`inline-flex items-center justify-center gap-2 font-semibold tracking-[-.01em] transition-all disabled:opacity-45 disabled:cursor-not-allowed cursor-pointer select-none ${variantClass[variant]} ${sizeClass[size]} ${className}`} disabled={disabled||loading} {...rest}>{loading?<Spinner className="h-4 w-4 border-[2px]"/>:null}{children}</button>});
export function Spinner({className="h-5 w-5 border-2"}:{className?:string}){return <span aria-hidden className={`inline-block animate-spin rounded-full border-current border-t-transparent opacity-70 ${className}`}/>}
export function Badge({children,tone="neutral"}:{children:ReactNode;tone?:"neutral"|"green"|"amber"|"red"|"blue"|"gold"|"slate"}){const tones:Record<string,string>={neutral:"bg-white/5 text-[#C8C5BE] border-white/10",green:"bg-emerald-500/10 text-emerald-300 border-emerald-400/20",amber:"bg-amber-500/10 text-amber-300 border-amber-400/20",red:"bg-red-500/10 text-red-300 border-red-400/20",blue:"bg-sky-500/10 text-sky-300 border-sky-400/20",gold:"bg-[#8A6A3A]/15 text-[#D2B47A] border-[#B99A62]/30",slate:"bg-slate-400/10 text-slate-300 border-slate-400/15"};return <span className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-semibold whitespace-nowrap ${tones[tone]}`}>{children}</span>}
export function aiStatusBadge(status:string){switch(status){case"COMPLETED":return{label:"اكتمل",tone:"green" as const};case"PENDING":return{label:"قيد الانتظار",tone:"amber" as const};case"PROCESSING":return{label:"جارٍ التنفيذ…",tone:"blue" as const};case"FAILED":return{label:"فشل",tone:"red" as const};default:return{label:status,tone:"neutral" as const}}}
export function presentationStatusBadge(status:string){switch(status){case"QUEUED":return{label:"في الانتظار",tone:"slate" as const};case"CURRENT":return{label:"يُعرض الآن",tone:"blue" as const};case"PRESENTED":return{label:"تم العرض",tone:"green" as const};case"SKIPPED":return{label:"تم التخطي",tone:"amber" as const};default:return{label:status,tone:"neutral" as const}}}
interface InputProps extends InputHTMLAttributes<HTMLInputElement>{label?:string;hint?:string;error?:string}
export const Input=forwardRef<HTMLInputElement,InputProps>(function Input({label,hint,error,className="",id,...rest},ref){const inputId=id??label?.toLowerCase().replace(/\s+/g,"-");return <div className="space-y-1.5">{label?<label htmlFor={inputId} className="block text-sm font-semibold text-[#E6E1D8]">{label}</label>:null}<input ref={ref} id={inputId} className={`h-11 w-full rounded-lg border bg-[#111F31] px-3 text-[15px] text-[#F7F5F0] placeholder:text-[#7f8995] focus:outline-none focus:ring-2 focus:ring-[#B99A62]/30 ${error?"border-red-400":"border-[#34465d]"} ${className}`} {...rest}/>{error?<p className="text-xs text-red-300">{error}</p>:hint?<p className="text-xs text-[#9A958B]">{hint}</p>:null}</div>})
export function Modal({open,onClose,title,children,wide=false}:{open:boolean;onClose?:()=>void;title?:string;children:ReactNode;wide?:boolean}){useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"&&onClose)onClose()};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[open,onClose]);return <AnimatePresence>{open?<div className="fixed inset-0 z-50 flex items-center justify-center p-4"><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="absolute inset-0 bg-[#070D15]/80" onClick={onClose} aria-hidden/><motion.div role="dialog" aria-modal="true" aria-label={title} initial={{opacity:0,y:14,scale:.985}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:8,scale:.99}} transition={{duration:.18,ease:"easeOut"}} className={`relative w-full ${wide?"max-w-2xl":"max-w-md"} max-h-[90vh] overflow-auto rounded-2xl border border-white/10 bg-[#18263A] shadow-2xl`}>{title?<div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><h2 className="font-display text-base font-semibold text-[#F7F5F0]">{title}</h2>{onClose?<button onClick={onClose} aria-label="إغلاق" className="rounded-lg p-1 text-[#A8A39A] hover:bg-white/5 hover:text-[#F7F5F0]">×</button>:null}</div>:null}<div className="px-5 py-4">{children}</div></motion.div></div>:null}</AnimatePresence>}
export function ConfirmDialog({open,onCancel,onConfirm,title,message,confirmLabel="تأكيد",danger=false,loading=false}:{open:boolean;onCancel:()=>void;onConfirm:()=>void;title:string;message:ReactNode;confirmLabel?:string;danger?:boolean;loading?:boolean}){return <Modal open={open} onClose={onCancel} title={title}><div className="space-y-5"><div className="text-sm leading-relaxed text-[#D0CCC4]">{message}</div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onCancel} disabled={loading}>إلغاء</Button><Button variant={danger?"danger":"primary"} onClick={onConfirm} loading={loading}>{confirmLabel}</Button></div></div></Modal>}
export function InlineMessage({tone,children}:{tone:"error"|"success"|"info";children:ReactNode}){const styles={error:"border-red-400/20 bg-red-500/10 text-red-200",success:"border-emerald-400/20 bg-emerald-500/10 text-emerald-200",info:"border-sky-400/20 bg-sky-500/10 text-sky-200"};return <div className={`rounded-xl border px-4 py-3 text-sm ${styles[tone]}`}>{children}</div>}
export function SectionTitle({children,sub}:{children:ReactNode;sub?:string}){return <div className="space-y-1"><h1 className="font-display text-2xl font-semibold tracking-tight text-[#F7F5F0]">{children}</h1>{sub?<p className="text-sm text-[#A8A39A]">{sub}</p>:null}</div>}
export function EmptyState({children}:{children:ReactNode}){return <div className="rounded-xl border border-dashed border-white/10 bg-[#18263A] px-6 py-14 text-center text-[#A8A39A]">{children}</div>}
