"use client";

import { forwardRef, useEffect, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode } from "react";
import { AnimatePresence, motion } from "framer-motion";

type ButtonVariant = "primary" | "secondary" | "ghost" | "danger" | "gold";
type ButtonSize = "sm" | "md" | "lg";
interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> { variant?: ButtonVariant; size?: ButtonSize; loading?: boolean; }
const variantClass: Record<ButtonVariant,string> = {
  primary:"bg-[#4b2228] text-[#fffaf3] hover:bg-[#5b2a31] border border-[#4b2228] shadow-[0_10px_24px_rgba(75,34,40,.16)]",
  secondary:"bg-[#fbf8f2] text-[#4b2228] border border-[#c9bda9] hover:border-[#b08a4a] hover:bg-[#f3ecdf]",
  ghost:"bg-transparent text-[#4b2228] hover:bg-[#4b2228]/5 border border-transparent",
  danger:"bg-[#7d2929] text-white hover:bg-[#922f2f] border border-transparent",
  gold:"bg-[#b08a4a] text-[#171512] hover:bg-[#c09a5a] border border-[#b08a4a] shadow-[0_10px_24px_rgba(176,138,74,.18)]",
};
const sizeClass: Record<ButtonSize,string> = { sm:"h-9 px-4 text-xs rounded-md", md:"h-11 px-5 text-sm rounded-md", lg:"h-13 px-7 text-base rounded-md" };
export const Button = forwardRef<HTMLButtonElement,ButtonProps>(function Button({variant="primary",size="md",loading,className="",disabled,children,...rest},ref){return <button ref={ref} className={`inline-flex items-center justify-center gap-2 font-semibold tracking-[-.01em] transition-all disabled:opacity-45 disabled:cursor-not-allowed cursor-pointer select-none ${variantClass[variant]} ${sizeClass[size]} ${className}`} disabled={disabled||loading} {...rest}>{loading?<Spinner className="h-4 w-4 border-[2px]"/>:null}{children}</button>});
export function Spinner({className="h-5 w-5 border-2"}:{className?:string}){return <span aria-hidden className={`inline-block animate-spin rounded-full border-current border-t-transparent opacity-70 ${className}`}/>}
export function Badge({children,tone="neutral"}:{children:ReactNode;tone?:"neutral"|"green"|"amber"|"red"|"blue"|"gold"|"slate"}){const tones:Record<string,string>={neutral:"bg-[#efe9df] text-[#554d45] border-[#d8cdbd]",green:"bg-[#e7efe7] text-[#31523a] border-[#bfd1c1]",amber:"bg-[#f5ead3] text-[#725525] border-[#ddc493]",red:"bg-[#f5e3e0] text-[#762e2e] border-[#dfb7b0]",blue:"bg-[#e8edf1] text-[#30495b] border-[#c4d0d8]",gold:"bg-[#b08a4a]/10 text-[#705426] border-[#b08a4a]/30",slate:"bg-[#e9e5de] text-[#4d4943] border-[#d0c8bc]"};return <span className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-semibold whitespace-nowrap ${tones[tone]}`}>{children}</span>}
export function aiStatusBadge(status:string){switch(status){case"COMPLETED":return{label:"اكتمل",tone:"green" as const};case"PENDING":return{label:"قيد الانتظار",tone:"amber" as const};case"PROCESSING":return{label:"جارٍ التنفيذ…",tone:"blue" as const};case"FAILED":return{label:"فشل",tone:"red" as const};default:return{label:status,tone:"neutral" as const}}}
export function presentationStatusBadge(status:string){switch(status){case"QUEUED":return{label:"في الانتظار",tone:"slate" as const};case"CURRENT":return{label:"يُعرض الآن",tone:"blue" as const};case"PRESENTED":return{label:"تم العرض",tone:"green" as const};case"SKIPPED":return{label:"تم التخطي",tone:"amber" as const};default:return{label:status,tone:"neutral" as const}}}
interface InputProps extends InputHTMLAttributes<HTMLInputElement>{label?:string;hint?:string;error?:string}
export const Input=forwardRef<HTMLInputElement,InputProps>(function Input({label,hint,error,className="",id,...rest},ref){const inputId=id??label?.toLowerCase().replace(/\s+/g,"-");return <div className="space-y-1.5">{label?<label htmlFor={inputId} className="block text-sm font-semibold text-[#3a342e]">{label}</label>:null}<input ref={ref} id={inputId} className={`h-11 w-full rounded-md border bg-[#fbf8f2] px-3 text-[15px] text-[#171512] placeholder:text-[#9a9084] focus:outline-none focus:ring-2 focus:ring-[#b08a4a]/30 ${error?"border-red-400":"border-[#cfc5b7]"} ${className}`} {...rest}/>{error?<p className="text-xs text-red-700">{error}</p>:hint?<p className="text-xs text-[#7f766c]">{hint}</p>:null}</div>})
export function Modal({open,onClose,title,children,wide=false}:{open:boolean;onClose?:()=>void;title?:string;children:ReactNode;wide?:boolean}){useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"&&onClose)onClose()};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[open,onClose]);return <AnimatePresence>{open?<div className="fixed inset-0 z-50 flex items-center justify-center p-4"><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="absolute inset-0 bg-[#171512]/65" onClick={onClose} aria-hidden/><motion.div role="dialog" aria-modal="true" aria-label={title} initial={{opacity:0,y:14,scale:.985}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:8,scale:.99}} transition={{duration:.18,ease:"easeOut"}} className={`relative w-full ${wide?"max-w-2xl":"max-w-md"} max-h-[90vh] overflow-auto rounded-lg border border-[#d8cdbd] bg-[#fbf8f2] shadow-2xl`}>{title?<div className="flex items-center justify-between border-b border-[#e1d8ca] px-5 py-4"><h2 className="font-display text-base font-semibold text-[#4b2228]">{title}</h2>{onClose?<button onClick={onClose} aria-label="إغلاق" className="rounded-md p-1 text-[#8d8276] hover:bg-[#eee7dc] hover:text-[#4b2228]">×</button>:null}</div>:null}<div className="px-5 py-4">{children}</div></motion.div></div>:null}</AnimatePresence>}
export function ConfirmDialog({open,onCancel,onConfirm,title,message,confirmLabel="تأكيد",danger=false,loading=false}:{open:boolean;onCancel:()=>void;onConfirm:()=>void;title:string;message:ReactNode;confirmLabel?:string;danger?:boolean;loading?:boolean}){return <Modal open={open} onClose={onCancel} title={title}><div className="space-y-5"><div className="text-sm leading-relaxed text-[#4f4840]">{message}</div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onCancel} disabled={loading}>إلغاء</Button><Button variant={danger?"danger":"primary"} onClick={onConfirm} loading={loading}>{confirmLabel}</Button></div></div></Modal>}
export function InlineMessage({tone,children}:{tone:"error"|"success"|"info";children:ReactNode}){const styles={error:"border-red-200 bg-red-50 text-red-800",success:"border-emerald-200 bg-emerald-50 text-emerald-800",info:"border-sky-200 bg-sky-50 text-sky-900"};return <div className={`rounded-md border px-4 py-3 text-sm ${styles[tone]}`}>{children}</div>}
export function SectionTitle({children,sub}:{children:ReactNode;sub?:string}){return <div className="space-y-1"><h1 className="font-display text-2xl font-semibold tracking-tight text-[#4b2228]">{children}</h1>{sub?<p className="text-sm text-[#7d746a]">{sub}</p>:null}</div>}
export function EmptyState({children}:{children:ReactNode}){return <div className="rounded-lg border border-dashed border-[#cfc5b7] bg-[#fbf8f2] px-6 py-14 text-center text-[#7d746a]">{children}</div>}
